// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateRoom():Promise<string>;

export function CreateRoomBot(arg1:string):Promise<string>;

export function CurrentTrack():Promise<main.Track>;

export function GetLibrary():Promise<Array<main.TrackLibrary>>;

export function Greet(arg1:string):Promise<string>;

export function NextMusic():Promise<void>;

export function PauseMusic():Promise<void>;

export function PlayMusic():Promise<void>;

export function RoomAlive():Promise<string>;

export function StopSrv():Promise<boolean>;
