// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRoom() {
  return window['go']['main']['App']['CreateRoom']();
}

export function CreateRoomBot(arg1) {
  return window['go']['main']['App']['CreateRoomBot'](arg1);
}

export function GetLibrary() {
  return window['go']['main']['App']['GetLibrary']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RoomAlive() {
  return window['go']['main']['App']['RoomAlive']();
}

export function StopSrv() {
  return window['go']['main']['App']['StopSrv']();
}
