// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRoom():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function RoomAlive():Promise<string>;

export function StopSrv():Promise<boolean>;
